service: ssrserverless-angular

plugins:
  - serverless-apigw-binary
  - serverless-plugin-custom-domain

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 192
  timeout: 10
  region: eu-west-1
  stackName: ${param:envName}-ssrserverless-angular

package:
  exclude:
    - ./**
  include:
    - 'node_modules/aws-serverless-express/**'
    - 'node_modules/binary-case/**'
    - 'node_modules/type-is/**'
    - 'node_modules/media-typer/**'
    - 'node_modules/mime-types/**'
    - 'node_modules/mime-db/**'
    - 'node_modules/@vendia/**'
    - 'dist/**'
    - 'lambda.js'

custom:
  apigwBinary:
    types:
      - '*/*'

resources:
  ClientTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ClientTable
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: N
      KeySchema:
        - AttributeName: customerId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

functions:
  api:
    handler: handler/server.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
  saveClient:
    handler: handler/client.saveClient
    events:
      - http:
          path: /saveClient
          method: post
