service: ssrserverless-angular

plugins:
  - serverless-apigw-binary
  - serverless-plugin-custom-domain

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 192
  timeout: 10
  region: eu-west-1
  stackName: ${param:envName}-ssrserverless-angular

package:
  exclude:
    - ./**
  include:
    - 'node_modules/aws-serverless-express/**'
    - 'node_modules/binary-case/**'
    - 'node_modules/type-is/**'
    - 'node_modules/media-typer/**'
    - 'node_modules/mime-types/**'
    - 'node_modules/mime-db/**'
    - 'node_modules/@vendia/**'
    - 'dist/**'
    - 'lambda.js'

custom:
  domain:
    name: '${param:envName}.cobuildr.agency'
    basePath: ''
  apigwBinary:
    types:
      - '*/*'

functions:
  api:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
