name: Deploy master branch
run-name: ${{ github.actor }} is deploying in staging 🚀
on:
  push:
    branches:
      - master

jobs:
  STAGING:
    permissions:
      id-token: write
      contents: read
    name: deploy on prod
    runs-on: ubuntu-latest
    env:
      NAME: "STAGING"
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Deploy on production environnement
        run: |
          echo "Running a job in the production environnement"
      - uses: actions/checkout@v3
      - name: 🧬🧬🧬 Use Node.js ${{ matrix.node-version }} - build project 🧬🧬🧬
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build:ssr
      - name: ⚡⚡⚡ serverless Deploy ⚡⚡⚡
        uses: serverless/github-action@v3.2
        with:
          args: deploy --stage staging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
